# Generated by Django 5.2.6 on 2025-10-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='post_content_media/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='posts.post')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('post', 'order')},
            },
        ),
    ]
