# Generated by Django 5.2.6 on 2025-11-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('message', 'Message'), ('follow', 'Follow')], default='', max_length=20),
        ),
    ]
